spring:
  application:
    name: ideai-gateway
  cloud:
    nacos:
      server-addr: forfries.com:8848 # Nacos服务地址
    gateway:
      enabled: true # 启用网关
      discovery:
        locator:
          enabled: true # 启用服务发现
      routes:
        - id: ideai-ai
          uri: lb://ideai-ai # 使用服务名称
          predicates:
            - Path=/ai/**
          
        - id: ideai-file
          uri: lb://ideai-file
          predicates:
            - Path=/file/**
            
        - id: ideai-user
          uri: lb://ideai-user
          predicates:
            - Path=/user/**

        - id: ideai-wxlogin
          uri: lb:ws://ideai-user
          predicates:
            - Path=/wxlogin


      globalcors:

        corsConfigurations:

          '[/**]':

            allowedOrigins: "*"

            allowedMethods: "*"

            allowedHeaders: "*"
server:
  port: 8081
