spring:
  application:
    name: ideai-ai
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

ai:
  deepseek:
    api-key: sk-d5ac698b9239400da8f454c9797e871c
    base-url: https://api.deepseek.com
    model: deepseek-chat
  dashscope:
    api-key: sk-82afef5897b94056b5c6f7ac763003e9
    base-url: https://dashscope.aliyuncs.com
    model: wanx-v1
    size: 1024*1024