spring:
  application:
    name: ideai-ai
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
ai:
  chat:
    deepseek:
      api-key: sk-5HiuQCIsaYvmg2004c55855e92074cDb98DfC22a5144D344
      model: DeepSeek-R1
      base-url: https://api.tofries.com
      max-token: 2000
  


